# Generated by Django 4.1.2 on 2022-12-18 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TileStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.IntegerField(default=0)),
                ('holder', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tile_stack', to='games.tilestackholder')),
            ],
        ),
        migrations.CreateModel(
            name='Meld',
            fields=[
                ('tilestack_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tiles.tilestack')),
                ('type', models.CharField(choices=[('kan', 'kan'), ('pon', 'pon'), ('chi', 'chi')], max_length=255)),
                ('suit', models.CharField(choices=[('dot', 'dot'), ('bamboo', 'bamboo'), ('character', 'character'), ('wind', 'wind'), ('dragon', 'dragon')], max_length=255)),
                ('is_opened', models.BooleanField()),
            ],
            bases=('tiles.tilestack',),
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(choices=[('dot', 'dot'), ('bamboo', 'bamboo'), ('character', 'character'), ('wind', 'wind'), ('dragon', 'dragon')], max_length=255)),
                ('name', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('east', 'east'), ('south', 'south'), ('west', 'west'), ('north', 'north'), ('green', 'green'), ('red', 'red'), ('white', 'white')], max_length=255)),
                ('position_in_tile_stack', models.IntegerField()),
                ('is_horizontal', models.BooleanField(default=False)),
                ('tile_stack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiles.tilestack')),
            ],
        ),
    ]
