# Generated by Django 4.1.2 on 2022-12-18 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.CharField(default='0', max_length=255)),
                ('is_full', models.BooleanField(default=False)),
                ('is_over', models.BooleanField(default=False)),
                ('random_state', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_round', models.IntegerField()),
                ('kan_counter', models.IntegerField(default=0)),
                ('in_call_phase', models.BooleanField(default=False)),
                ('last_discarded_tile', models.JSONField(default=dict)),
                ('next_wind_to_play', models.CharField(choices=[('east', 'east'), ('south', 'south'), ('west', 'west'), ('north', 'north')], default='south', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TileStackHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('game_hand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.hand')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_game', models.IntegerField()),
                ('prevailing_wind', models.CharField(choices=[('east', 'east'), ('south', 'south'), ('west', 'west'), ('north', 'north')], max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=25000)),
                ('wind', models.CharField(choices=[('east', 'east'), ('south', 'south'), ('west', 'west'), ('north', 'north')], max_length=255)),
                ('is_dealer', models.BooleanField(default=False)),
                ('can_play', models.BooleanField(default=False)),
                ('possible_calls', models.JSONField(default=list)),
                ('call_sent', models.JSONField(default=dict)),
                ('in_tenpai', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hand',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.round'),
        ),
        migrations.AddField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(through='games.Player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlayerMeld',
            fields=[
                ('tilestackholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.tilestackholder')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.player')),
            ],
            bases=('games.tilestackholder',),
        ),
        migrations.CreateModel(
            name='PlayerHand',
            fields=[
                ('tilestackholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.tilestackholder')),
                ('is_opened', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.player')),
            ],
            bases=('games.tilestackholder',),
        ),
        migrations.CreateModel(
            name='PlayerDiscard',
            fields=[
                ('tilestackholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.tilestackholder')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.player')),
            ],
            bases=('games.tilestackholder',),
        ),
    ]
